[pytest]
DJANGO_SETTINGS_MODULE = nouvelair.settings
base_url = http://127.0.0.1:8000
python_files = test_*.py
python_classes = Test*
python_functions = test_*
testpaths = tests
addopts = --ds=nouvelair.settings --ignore=tests/unit/test_models_promotions.py --screenshot=only-on-failure --output=reports/playwright/
markers =
    smoke: Smoke tests
    owasp: OWASP security tests
    responsive: Responsive design tests
    a11y: Accessibility tests
    unit: Unit tests
    integration: Integration tests
    api: API tests
    e2e: End-to-end tests
    security: Security tests
    performance: Performance tests
    bdd: BDD/Behave tests
    visual: Visual regression tests
    regression: Regression tests
    system: Tests système (LiveServer + navigateur)
    selenium: Selenium tests
